### ISSUE TITLE
infinity food

### ISSUE THREAD

**Issue by jappi** [space-jam-/vampirism#217]
if u try to train invoker w/o 400 lumber u will get -10 food and can grade it for -999(9).
![2015-07-28_00002](https://cloud.githubusercontent.com/assets/13433394/8943608/2d638d00-3584-11e5-8a26-0888c38e8122.jpg)
p.s. hope you understand my ruenglish ^_^

**Comment by space-jam-** [comment]
This should have been fixed in b7280f77577f171e9b2f3782730547238a1d953f
