### ISSUE TITLE
Humans building in areas Vampire can't reach

### ISSUE THREAD

**Issue by decoy11** [space-jam-/vampirism#225]
![Alt Text](http://i.imgur.com/Kpoi0u3.jpg)

![Alt Text](http://i.imgur.com/mfIqhDz.jpg)

![Alt Text](http://i.imgur.com/pdRoOte.jpg)

**Comment by space-jam-** [comment]
These areas are closed in fd8de6d51081408c88170a00afe978e702c9bce0 if you find more, reopen the issue.

**Comment by decoy11** [comment]
More places vamps get into

![dota2 2015-09-03 18-10-23-77](https://cloud.githubusercontent.com/assets/6022241/9674602/5e9c623e-5267-11e5-961a-206eb54d8331.png)
![dota2 2015-09-03 18-09-27-65](https://cloud.githubusercontent.com/assets/6022241/9674603/5ea3d3e8-5267-11e5-98f9-1ae48f571860.png)
![dota2 2015-09-03 18-09-11-79](https://cloud.githubusercontent.com/assets/6022241/9674604/5ea60406-5267-11e5-9ae9-625344fb2546.png)
![dota2 2015-09-03 18-07-47-40](https://cloud.githubusercontent.com/assets/6022241/9674605/5ea9ba9c-5267-11e5-98e3-66eff5ee6c46.png)
![dota2 2015-09-03 18-06-25-55](https://cloud.githubusercontent.com/assets/6022241/9674606/5eb1980c-5267-11e5-811f-52dd84bba8c0.png)

**Comment by decoy11** [comment]
![dota2 2015-09-05 04-44-46-70](https://cloud.githubusercontent.com/assets/6022241/9699172/6ac53000-538d-11e5-9d7f-0d004e7d9428.png)
![dota2 2015-09-05 04-41-40-25](https://cloud.githubusercontent.com/assets/6022241/9699173/6ae13d4a-538d-11e5-860d-2e749030269c.png)
