### ISSUE TITLE
Humans blinking off map

### ISSUE THREAD

**Issue by decoy11** [space-jam-/vampirism#226]
![Alt Text](http://i.imgur.com/6YhMaFf.jpg)
![Alt Text](http://i.imgur.com/1TMpS0l.jpg)
![Alt Text](http://i.imgur.com/ght1DtC.jpg)
![Alt Text](http://i.imgur.com/YTzj1f6.jpg)

**Comment by space-jam-** [comment]
Should've been fixed in b19a872271ded890fc72c7c54b636f2638de7dd3.
