### ISSUE TITLE
Humans attacking other players building abuse and Mini-vamp retain control of slayer abuse

### ISSUE THREAD

**Issue by decoy11** [space-jam-/vampirism#242]
Other players can destroy other players buildings if they wish to ruin a game. Mini-vamps from dead humans can control their slayers if they are still alive and attack other player's buildings to ruin a game.

**Comment by space-jam-** [comment]
I've fixed the bug where players kept their slayers in 0.15, are players able to attack other peoples buildings in another way? Remember that this is allowed by default if a base isn't claimed. Closing this issue, reopen if I missed something.
