### ISSUE TITLE
Invisible units not being detected by truesight

### ISSUE THREAD

**Issue by decoy11** [space-jam-/vampirism#268]
I had a game where truesight from the ward tower and tracker did not reveal an assassin. I am not sure if vamp was not being detected.

**Comment by HiroSakuya** [comment]
I second this, please fix it. It is more annoying that any bug so far. The Assassin is being abused to kill workers and humans can't farm anymore. Vampire just keeps getting fat. We cannot do anything to reveal that assassin. Thank

**Comment by space-jam-** [comment]
Should have been fixed in b4f21c1b4038786e86c23d4c4df7e97b1c9e0b72. Re open the issue if not.
